log_file : "model_train.log"

train_files:
  # 1000个股票, 365天数据
  - ../training_data/data.bin.20221116_1501
  # 测试
  # - "../training_data/data.bin.20221115_2026"
#预处理instance: 处理label, 过滤fid等
train_data:
  validate_date : "20221111"      # 验证集: 没有label且时间在这个后面
  label:
    method : binarize
    args: 
      key : next_7d_close_price   # 由于存在停牌, 故时间特征可能会导致特征穿越
      threshold : 0.1   #
  min_fid_occurrence : 80    # 每个fid最少出现几次
  debug:                 # debug 函数
    fid_whitelist:                # 要debug的fid, 训练的时候也只会训练这些
      # - 1444932513133819623
      # - 1444015990897181305
      # - 1450672333743350316
      # - 1453955548291422233
    slot_whitelist: 
      # - 100
      # - 507
      # - 82
      # - 83
    slot_blacklist:
      # - 506   # 日期黑名单
    


model: 
  loss_type: cross_entropy
  # l2_lambda : 0        # 如果fid出现多次，则只计算一次l2_loss
  # global_bias : True
  optimizer : 
    # type: AdagradOptimizer
    # type: MomentumOptimizer
    # momentum : 0.9       # 动量

    type: GradientDescentOptimizer  # 效果最好
    learning_rate: 0.001
  mini_batch:
    batch_size: 1000
    epoch : 20000

# 调参经验： 
#  1. learning rate 
#      1e-2: 2.5太高了，直接学飞
#      1e-3: 0.037
#      1e-4: 0.085 会导致稀疏特征学得慢
#  2. l2_lambda (看着没什么用)
#      0 :    diff = 0.025
#      1e-3 : diff = 0.035
#      1e-4 : diff = 0.032
#      1e-5 : diff = 0.042
#  3. 有无global_bias diff 0.03 vs 0.02
#  4. adagrad: 学习率要调整为0.01, 但是扔没有明显收益
