# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\"y\n\rFeatureColumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04slot\x18\x02 \x01(\x04\x12\x0c\n\x04\x66ids\x18\x03 \x03(\x04\x12\x13\n\x0braw_feature\x18\x04 \x03(\t\x12\x1a\n\x12\x65xtracted_features\x18\x05 \x03(\t\x12\r\n\x05\x64\x65nse\x18\x06 \x03(\x02\"\xbd\x01\n\x08Instance\x12\x1f\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x0e.FeatureColumn\x12#\n\x05label\x18\x02 \x03(\x0b\x32\x14.Instance.LabelEntry\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07ts_code\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x10\n\x08total_mv\x18\x06 \x01(\x03\x1a,\n\nLabelEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01*C\n\x0cTimeInterval\x12\x07\n\x03\x44\x61y\x10\x00\x12\x08\n\x04Week\x10\x01\x12\t\n\x05Month\x10\x02\x12\x0b\n\x07Quarter\x10\x03\x12\x08\n\x04Year\x10\x04*\x1c\n\x08\x43urrency\x12\x07\n\x03\x43NY\x10\x00\x12\x07\n\x03USD\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INSTANCE_LABELENTRY']._options = None
  _globals['_INSTANCE_LABELENTRY']._serialized_options = b'8\001'
  _globals['_TIMEINTERVAL']._serialized_start=330
  _globals['_TIMEINTERVAL']._serialized_end=397
  _globals['_CURRENCY']._serialized_start=399
  _globals['_CURRENCY']._serialized_end=427
  _globals['_FEATURECOLUMN']._serialized_start=15
  _globals['_FEATURECOLUMN']._serialized_end=136
  _globals['_INSTANCE']._serialized_start=139
  _globals['_INSTANCE']._serialized_end=328
  _globals['_INSTANCE_LABELENTRY']._serialized_start=284
  _globals['_INSTANCE_LABELENTRY']._serialized_end=328
# @@protoc_insertion_point(module_scope)
